Introduction and Overview sections
p1onerka/ANTLR-term-paper pull request #1
Opened 2024-10-21 12:04 UTC by p1onerka

2024-10-22 19:04 UTC, Kakadu requested changes
Ставьте ещё ENTER в конце предложения, чтобы было проще оставлять комменты.

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +\section{Вступление}
В шаблоне написано, что это введение

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +В настоящее время существует множество задач, для которых необходимы специфические синтаксические анализаторы. К таким задачам относятся разработка компиляторов и интерпретаторов, обработка пользоват
> требует от программиста (жаргон?) знаний специальной теории, а зачастую и специальных языков программирования.

Как раз генераторы анализаторов и требуют большей теории от программиста и знания специальных языков (рисования грамматик). так что мотивация хромает

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +В настоящее время существует множество задач, для которых необходимы специфические синтаксические анализаторы. К таким задачам относятся разработка компиляторов и интерпретаторов, обработка пользоват
>  были внедрены (изобретены?) инструменты

созданы

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +В настоящее время существует множество задач, для которых необходимы специфические синтаксические анализаторы. К таким задачам относятся разработка компиляторов и интерпретаторов, обработка пользоват
> На данный момент такие инструменты нашли широкое применение в индустрии и вытеснили аналогичную ручную разработку (голословно?)

Ровно наоборот

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +Одним из самых распространенных генераторов является ANTLR (Another Tool for Language Recognition). На данный момент он официально поддерживает восемь императивных (ооп? а с++ номинально и функционал
Нет, с++ не функциональный

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +Благодаря вариативности и легкости применения, при разработке синтаксического анализатора использование ANTLR часто является требованием компании. При этом, актуальная его версия не поддерживает ни о
> Благодаря вариативности и легкости применения

Я не знаю, что такое вариативность.
Легкость применения только для тех языков (грамматик), которые ANTLR умеет

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +Благодаря вариативности и легкости применения, при разработке синтаксического анализатора использование ANTLR часто является требованием компании. При этом, актуальная его версия не поддерживает ни о
Последнее предложение абзаца надо как-то переделать. Мотивация хромает.

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +Таким образом была поставлена задача о расширении функциональности ANTLR на какой-либо из общепринятых (?) функциональных языков. В качестве целевого языка был выбран OCaml благодаря его сходству с д
> какой-либо из общепринятых (?) функциональных языков

Я вам такого не говорил

> В качестве целевого языка был выбран OCaml благодаря его сходству с другими языками, что позволяет адаптировать код с минимальными усилиями.

Про сходство плохо написано. Напишите явнее, что имеется в виду буква О.

Про то, что усилия будут минимальные вы не сможете говорить, пока не сделаете.

2024-10-22 19:04 UTC, Kakadu commented on main.tex
> +\end{enumerate}
Я не верен, что дюна нужна. Оставьте на потом.

F# и Haskell имеют мало отношения к работе. Оставьте на потом

Про Cup, Lark впервые слышу.

2024-10-28 08:11 UTC, p1onerka commented on main.tex
Поправила введение. 
Обзор тогда я пока не трогаю, возможно, с ним станет более понятно дальше в процессе работы. На той неделе составила себе список "маст-хев" файлов для генерации первого маленького парсера, потихоньку их перевожу. Основная проблема пока -- Maven, который не желает генерировать мне .jar файл для тестовых запусков. Подозреваю, что, чтобы его оживить, нужно написать хотя бы один тест на мой OCaml-модуль. Но не очень понятно, что именно тестировать, учитывая, что я даже запустить не могу. На этой неделе дедлайны закончились, поэтому надеюсь сделать больше, чем на предыдущей

2024-10-28 09:10 UTC, Kakadu commented on main.tex
> +Кроме того, интеграция императивного кода анализатора в функциональный код остального проекта может оказаться сложным и трудозатратным процессом (или убрать эту мотивацию вообще?).
Лучше сказать, что интеграция кода на одном языке программирования в проект на другом может быть сложной.

2024-10-28 09:11 UTC, Kakadu commented on main.tex
> +и возможностей функциональной парадигмы, которые позволят сделать результат более эффективным.
Все спросят, что именно за эффективность задумывается.

2024-10-28 09:11 UTC, Kakadu commented on main.tex
Стало лучше.

2024-10-28 09:18 UTC, p1onerka commented on main.tex
> +и возможностей функциональной парадигмы, которые позволят сделать результат более эффективным.
Упоминание каррирования комиссию не устроит? Или, например, рассуждение о том, что код на OCaml получится компактнее Java, но с той же функциональностью. Но вообще, я оставила во введении несколько абстрактных фраз, которые, возможно, потом придется вырезать во избежание вопросов. В конце концов, меня же могут спросить, почему я на эксперименте не показала повышение эффективности, и я не знаю, как на такое отвечать

2024-10-28 10:46 UTC, Kakadu commented on main.tex
> +и возможностей функциональной парадигмы, которые позволят сделать результат более эффективным.
> код на OCaml получится компактнее Java

Вас спросят откуда данные, и как это влияет на эффективность.

2024-11-02 12:42 UTC, Kakadu approved these changes
ACK

2024-11-02 12:42 UTC, Kakadu commented on main.tex
> +Все тестирование при этом происходит внутри инструмента, абстрагированно от пользователя.
Могут подумать, что порождается анализатор, внутри которого какое-то тестирование анализатора. НАверное, Вы имели в виду, что генератор протестирован не нами и до нас и ему можно доверять.

2024-11-02 12:42 UTC, Kakadu commented on practice/010_task.tex
> +\end{enumerate}
До апробации и внедрения скорее всего в этом семестре не дойдет.
Поэтому валидация смешается с тестированием.
Вообще, эти пункты можно исправить будет потом, никто не будет проверять, что они не поменялись.

2024-11-02 12:43 UTC, Kakadu commented on practice/010_task.tex
> +    \item реализовать в инструменте ANTLR поддержку генерации на языке OCaml;
Такое ощущение, что цель у вас стала первой задачей. 
Пересмотрите шаблон.

2024-12-09 14:01 UTC, merged